### PR TITLE
First pass at a UBI token in Scrypto.

### PR DESCRIPTION
**Pull request by michaelwoodson**
A UBI token that allocates 1 token per person per epoch. Ideally there would be a 20% burn on each transaction but currently the burn is optional. Will enforce when `RECALLABLE` support is added.

It was fun to learn and refreshing to get introduced to Scrypto!

### CODE REVIEW

**Review by cbisaillon — CHANGES_REQUESTED** [review]
Thanks for this example. Here are some changes that you would need to do before I can merge on main. Can you also add more comments to help explain your code ?

**Comment by cbisaillon** [comment]
@michaelwoodson I suggest joining the Scrypto mailing list to be eligible to 75$ in XRD when I merge this PR, if you have not already did: https://developers.radixdlt.com/devprogram

**Comment by michaelwoodson** [comment]
@cbisaillon Thanks for the detailed feedback! Just pushed a change that should incorporate all the requested changes. I also signed up for the mailing list a couple weeks ago.

**Comment by cbisaillon** [comment]
Good job. Thank you for doing the requested changes !

**Review by cbisaillon — APPROVED** [review]

**Comment by cbisaillon** [comment]
You should receive your 75$ worth of XRD in the next few of weeks

**Comment by michaelwoodson** [comment]
Very good, thank you!

**Pull request merged**
